### PR TITLE
Invalid schema

### LINKED ISSUE #174: Invalid audit table name with schema
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | 2.4.7
| PHP version          | 8.2
| Database             | PostgreSQL

#### Summary

Invalid computed audit table name if I use Doctrine schema

#### Current behavior

prefixschema.%table%suffix

#### How to reproduce

create entity with schema 

#### Expected behavior

schema.prefix%table%suffix

### PR DESCRIPTION
**Pull request by dmitryuk**
Closes #174 

Don't forget please to make a new release

### CODE REVIEW

**Comment by dmitryuk** [comment]
Cs fixer failed on files I never touched

**Comment by dmitryuk** [comment]
@DamienHarper please accept PR, we need to fix our code

**Comment by GityaMan** [comment]
Are there any updates on this PR?

**Comment by GityaMan** [comment]
@DamienHarper , Is there a planned release of this fix?

**Pull request merged**
