### PR TITLE
Update `doctrine/orm` to 3.0.0

### PR DESCRIPTION
**Pull request by JeroenMoonen**
After updating, [DamienHarper/auditor-bundle](https://github.com/DamienHarper/auditor-bundle) can be updated as well.

### CODE REVIEW

**Review by maxhelias — COMMENTED** [review]
If there are no changes, why remove compatibility with ^2.13?
BTW, I haven't looked at how the package works, but no change to be compatible with ORM 3 seems suspicious to me.

**Comment by DamienHarper** [comment]
@JeroenMoonen Supporting ORM 3.x is way more complex than updating the `composer.json` file. Many BC breaks were introduced in ORM 3.x (see https://github.com/doctrine/orm/blob/3.1.x/UPGRADE.md#upgrade-to-30)
Then, supporting both ORM 2.x and 3.x is another piece of work.

**Review by DamienHarper — CHANGES_REQUESTED** [review]
This is not sufficient to make this lib compliant with ORM 3.x

**Comment by DamienHarper** [comment]
Closed in favor of #207

**Pull request closed without merging**
